apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
  namespace: mlops
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: my-local-storage
  local: 
    path: /media/caonv/hdd/k8s-volumes/mlflow
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - master-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: mlops
spec:
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-deployment
  template:
    metadata:
      labels:
        app: mlflow-deployment
    spec:
      containers:
      - name: myapp
        image: ghcr.io/mlflow/mlflow:v2.0.1
        command: ["mlflow", "server", "--host", "0.0.0.0", "--backend-store-uri", "sqlite:///mlflow/my.db", "--artifacts-destination", "/mlflow/artifacts"] 
        resources:
          limits:
            memory: "4096Mi"
            cpu: "2"
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /mlflow
            name: mlflow-data
      volumes: 
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-svc
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: mlflow-deployment
  ports:
  - port: 5000

